sudo: required
dist: trusty
language: cpp

services:
  - docker

branches:
  only:
    - master
    - develop

before_install:
  - docker build -t travis-build -f infrastructure/tools/Dockerfile .

script:
  # Common style check
  - docker run travis-build infrastructure/tools/checkstyle.sh $TRAVIS_COMMIT_RANGE
  # Clang, build debug and release witn boost logger, run debug tests
  - docker run travis-build /bin/bash -c "./waf configure --init --logger=boost build_debug build_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build build/debug/testrunner
  # Clang, build debug and release with log4cplus logger, run debug tests
  - docker run travis-build /bin/bash -c "./waf clean_debug clean_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build /bin/bash -c "./waf configure --init --logger=log4cplus build_debug build_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build build/debug/testrunner
  # Clang, build debug and release without logger, run debug tests
  - docker run travis-build /bin/bash -c "./waf clean_debug clean_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build /bin/bash -c "./waf configure --init build_debug  build_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build build/debug/testrunner
  # GCC, build debug and release with boost logger, run debug tests
  - docker run travis-build /bin/bash -c "./waf clean_debug clean_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build /bin/bash -c "CXX=g++ ./waf configure --init --logger=boost build_debug build_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build build/debug/testrunner
  # GCC, build debug and release with log4cplus logger, run debug tests
  - docker run travis-build /bin/bash -c "./waf clean_debug clean_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build /bin/bash -c "CXX=g++ ./waf configure --init --logger=log4cplus build_debug build_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build build/debug/testrunner
  # GCC, build debug and release without logger, run debug tests
  - docker run travis-build /bin/bash -c "./waf clean_debug clean_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build /bin/bash -c "CXX=g++ ./waf configure --init build_debug build_release"
  - docker commit $(docker ps -l -q) travis-build
  - docker run travis-build build/debug/testrunner
